(function(){'use strict';
const C=window.KURDUWADI_CONFIG||{};
if(!document.body.classList.contains('premium-home')||!C.SUPABASE_URL||!C.SUPABASE_ANON_KEY)return;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(rows){const sec=document.createElement('section');sec.className='section citizen-home-section';sec.innerHTML='<div class="section-head"><div><div class="section-label">OUR CITIZENS</div><h2>👥 मंजूर नागरिक प्रोफाइल</h2><p class="section-sub">कुर्डुवाडीशी जोडलेली आपली माणसे — नागरिकांच्या परवानगीने प्रकाशित.</p></div><a class="text-btn" href="directory.html">डिरेक्टरी →</a></div><div class="citizen-home-grid">'+(rows.length?rows.map(x=>'<article class="citizen-home-card"><div class="citizen-home-avatar">'+esc((x.name||'क').trim().charAt(0))+'</div><div><b>'+esc(x.name)+'</b><span>'+esc([x.job,x.city].filter(Boolean).join(' · ')||'कुर्डुवाडी')+'</span>'+(x.work_fields?.length?'<small>'+esc(x.work_fields.slice(0,2).join(' • '))+'</small>':'')+'</div></article>').join(''):'<div class="citizen-home-empty">अद्याप मंजूर नागरिक प्रोफाइल उपलब्ध नाहीत.</div>')+'</div>';const anchor=document.querySelector('.updates-section')||document.querySelector('main');anchor?.parentNode.insertBefore(sec,anchor)}
async function load(){const url=C.SUPABASE_URL.replace(/\/$/,'')+'/rest/v1/profiles?select=id,name,job,city,work_fields&status=eq.approved&is_public=eq.true&order=created_at.desc&limit=6';try{const r=await fetch(url,{headers:{apikey:C.SUPABASE_ANON_KEY,Authorization:'Bearer '+C.SUPABASE_ANON_KEY}});if(!r.ok)throw Error(r.status);render(await r.json())}catch(e){console.warn('Citizen profiles:',e);render([])}}
function init(){const marker=document.querySelector('.home-pride-section')||document.querySelector('.updates-section');if(!marker)return;const io=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)){io.disconnect();load()}},{rootMargin:'500px'});io.observe(marker)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
