const {SUPABASE_URL,SUPABASE_ANON_KEY}=window.KURDUWADI_CONFIG;
let supabaseClient=null,allDirectoryRows=[],activeDirectoryFilter='all';
if(window.supabase&&SUPABASE_URL?.startsWith('http')&&SUPABASE_ANON_KEY)supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const educationFallback=[
 {business_name:'K.N. Bhise Arts, Commerce and Vinayakrao Patil Science College',category:'शिक्षण / शिक्षक',address:'भोसरे, कुर्डूवाडी परिसर, महाराष्ट्र 413208',google_maps_link:'https://www.google.com/maps/search/?api=1&query=K.N.Bhise+College+Kurduwadi'},
 {business_name:'Government Industrial Training Institute (ITI)',category:'शिक्षण / शिक्षक',address:'कुर्डूवाडी शहर, महाराष्ट्र 413208',google_maps_link:'https://www.google.com/maps/search/?api=1&query=Government+Industrial+Training+Institute+Kurduwadi'},
 {business_name:'Shri Tuljabhavani College of Education for Women',category:'शिक्षण / शिक्षक',address:'बार्शी बायपास रोड, कुर्डूवाडी',google_maps_link:'https://www.google.com/maps/search/?api=1&query=Shri+Tuljabhavani+College+of+Education+for+Women+Kurduwadi'},
 {business_name:'Jivhala Sanskar Vidyamandir',category:'शिक्षण / शिक्षक',address:'संभाजी नगर, बागल नगर, कुर्डूवाडी — 413208',google_maps_link:'https://www.google.com/maps/search/?api=1&query=Jivhala+Susanskar+Vidyamandir+Kurduwadi'}
];
async function loadCitizens(){const grid=document.getElementById('citizenGrid');if(!grid)return;if(!supabaseClient){grid.innerHTML='<div class="citizen-empty"><strong>Database configuration तपासा.</strong><span>Supabase configuration उपलब्ध नाही.</span></div>';return}grid.innerHTML='<div class="citizen-empty"><strong>Directory load होत आहे…</strong><span>कृपया थोडा वेळ थांबा.</span></div>';const q=(document.getElementById('searchInput')?.value||'').trim(),city=(document.getElementById('cityFilter')?.value||'').trim();let query=supabaseClient.from('kurduwadi_directory').select('business_name,category,contact_number,email,address,timings,google_maps_link,status,is_approved').eq('status','approved').eq('is_approved',true).order('business_name',{ascending:true}).limit(100);if(city)query=query.ilike('address',`%${city}%`);if(q)query=query.or(`business_name.ilike.%${q}%,category.ilike.%${q}%,contact_number.ilike.%${q}%,email.ilike.%${q}%,address.ilike.%${q}%`);const {data,error}=await query;if(error){console.error(error);grid.innerHTML='<div class="citizen-empty"><strong>Directory माहिती load झाली नाही.</strong><span>कृपया पुन्हा प्रयत्न करा.</span></div>';return}allDirectoryRows=data||[];const count=document.getElementById('directoryCount');if(count)count.textContent=allDirectoryRows.length;renderDirectory()}
function renderDirectory(){const grid=document.getElementById('citizenGrid');if(!grid)return;let rows=allDirectoryRows;if(activeDirectoryFilter!=='all')rows=rows.filter(p=>matchesCategory(p.category,activeDirectoryFilter));if(!rows.length&&activeDirectoryFilter==='education'&&!document.getElementById('searchInput')?.value&&!document.getElementById('cityFilter')?.value)rows=educationFallback;if(!rows.length){grid.innerHTML='<div class="citizen-empty"><strong>या श्रेणीत नोंदी उपलब्ध नाहीत.</strong><span>दुसरी श्रेणी किंवा शोध बदलून पुन्हा पहा.</span></div>';return}grid.innerHTML=rows.map(p=>{const name=escapeHtml(p.business_name||'कुर्डुवाडी नागरिक'),category=escapeHtml(p.category||'इतर'),initial=escapeHtml((p.business_name||'कु').trim().charAt(0).toUpperCase()),map=p.google_maps_link?safeUrl(p.google_maps_link):'',phone=p.contact_number?normalizePhone(p.contact_number):'',wa=phone?`https://wa.me/${phone}?text=${encodeURIComponent('नमस्कार, '+(p.business_name||'आपल्या Directory माहितीबद्दल')+' संदर्भात संपर्क करायचा आहे.')}`:'',email=p.email?safeEmail(p.email):'';return `<article class="citizen-card"><div class="citizen-top"><div class="citizen-avatar">${initial}</div><div class="citizen-heading"><h3>${name}</h3><span class="citizen-category">● ${category}</span></div></div><span class="citizen-status">✓ Verified</span><div class="citizen-info">${p.address?`<p>📍 ${escapeHtml(p.address)}</p>`:''}${p.contact_number?`<p>📱 ${escapeHtml(p.contact_number)}</p>`:''}${p.email?`<p>✉️ <a href="mailto:${email}">${escapeHtml(p.email)}</a></p>`:''}${p.timings?`<p>🕒 ${escapeHtml(p.timings)}</p>`:''}</div><div class="citizen-actions">${wa?`<a class="citizen-action primary" href="${wa}" target="_blank" rel="noopener">💬 WhatsApp</a>`:''}${p.contact_number?`<a class="citizen-action" href="tel:${escapeAttr(p.contact_number)}">📞 कॉल</a>`:''}${email?`<a class="citizen-action" href="mailto:${email}">✉️ Email</a>`:''}${map?`<a class="citizen-action" href="${map}" target="_blank" rel="noopener">📍 नकाशा</a>`:''}</div></article>`}).join('')}
function matchesCategory(category,filter){const c=String(category||'').toLowerCase();const groups={professionals:['professional','professionals','नोकदार','नोकरी','employee','job'],business:['business','व्यवसाय','shop','दुकान','दुकानदार','किराणा'],agriculture:['agriculture','शेती','शेतकरी','farm','farming'], 'skilled-trades':['skilled','trade','कुशल','कामगार','कारागीर','technician','driver','plumber','electrician'],education:['education','शिक्षण','teacher','शिक्षक'],students:['student','विद्यार्थी'],mentors:['mentor','मार्गदर्शक','guide','consultant','सेवा','service'],other:[]};return groups[filter]?.some(k=>c.includes(k))||(filter==='other'&&!Object.entries(groups).filter(([k])=>k!=='other').flatMap(([,v])=>v).some(k=>c.includes(k)))}
function normalizePhone(s){let n=String(s||'').replace(/\D/g,'');if(n.length===10)n='91'+n;return n}function safeEmail(s){return String(s||'').trim().replace(/[^a-zA-Z0-9.!#$%&'*+/=?^_`{|}~@-]/g,'')}function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function escapeAttr(s){return String(s??'').replace(/[^0-9+()\- ]/g,'')}function safeUrl(s){const u=String(s??'').trim();return /^https?:\/\//i.test(u)?escapeHtml(u):'#'}
window.loadCitizens=loadCitizens;
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('.directory-filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.directory-filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeDirectoryFilter=btn.dataset.filter||'all';renderDirectory()}));document.getElementById('searchInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();loadCitizens()}});loadCitizens()});
