-- Notice Board migration for existing Kurduwadi portal
create table if not exists public.noticeboard (
 id bigint generated by default as identity primary key,
 type text not null default 'other' check (type in ('birth','marriage','achievement','obituary','lost_found','other')),
 title text not null,
 description text not null,
 person_name text,
 notice_date date,
 contact text,
 image_url text,
 status text not null default 'pending' check (status in ('pending','approved','rejected')),
 published boolean not null default false,
 created_at timestamptz not null default now()
);
alter table public.noticeboard enable row level security;
drop policy if exists "public approved noticeboard" on public.noticeboard;
create policy "public approved noticeboard" on public.noticeboard for select using (status='approved' and published=true);
drop policy if exists "public noticeboard submissions" on public.noticeboard;
create policy "public noticeboard submissions" on public.noticeboard for insert to anon, authenticated with check (status='pending' and published=false);
drop policy if exists "admin manage noticeboard" on public.noticeboard;
create policy "admin manage noticeboard" on public.noticeboard for all to authenticated using (public.is_admin()) with check (public.is_admin());
create index if not exists noticeboard_type_status_idx on public.noticeboard(type,status,published,notice_date desc,created_at desc);
