-- KURDUWADI PRIDE PERSONALITIES
create table if not exists public.personalities (
  id bigint generated by default as identity primary key,
  name text not null,
  kurduwadi_relation text,
  field text,
  current_position text,
  organization text,
  education text,
  birthplace text,
  major_work text,
  achievements text,
  awards text,
  social_contribution text,
  references text,
  profile_url text,
  image_url text,
  status text default 'pending' check (status in ('pending','approved','rejected')),
  published boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.personality_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  relation text,
  field text,
  reason text not null,
  reference_url text,
  image_url text,
  contact text,
  status text default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz default now()
);

alter table public.personalities enable row level security;
alter table public.personality_submissions enable row level security;

drop policy if exists "public approved personalities" on public.personalities;
create policy "public approved personalities" on public.personalities for select using (status='approved' and published=true);

drop policy if exists "admin manage personalities" on public.personalities;
create policy "admin manage personalities" on public.personalities for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public personality submissions" on public.personality_submissions;
create policy "public personality submissions" on public.personality_submissions for insert to anon, authenticated with check (status='pending');

drop policy if exists "admin manage personality submissions" on public.personality_submissions;
create policy "admin manage personality submissions" on public.personality_submissions for all to authenticated using (public.is_admin()) with check (public.is_admin());

create index if not exists personalities_status_published_idx on public.personalities(status,published,created_at desc);
create index if not exists personality_submissions_status_idx on public.personality_submissions(status,created_at desc);
