-- KURDUWADI CITY PORTAL - PHASE 4 FINAL SQL
-- Safe to run after NOTICEBOARD table creation.

-- Ensure status/published exist on core workflow tables
alter table if exists public.news add column if not exists status text default 'pending';
alter table if exists public.news add column if not exists published boolean default false;
alter table if exists public.events add column if not exists status text default 'pending';
alter table if exists public.events add column if not exists published boolean default false;
alter table if exists public.ideas add column if not exists status text default 'pending';
alter table if exists public.ideas add column if not exists published boolean default false;

-- Noticeboard was created in the previous fix; create it defensively if absent.
create table if not exists public.noticeboard (
 id bigint generated by default as identity primary key,
 type text not null default 'other',
 title text not null,
 description text not null,
 person_name text,
 notice_date date,
 contact text,
 image_url text,
 status text not null default 'pending',
 published boolean not null default false,
 created_at timestamptz not null default now()
);

-- Normalize nulls
update public.news set status='pending' where status is null;
update public.news set published=false where published is null;
update public.events set status='pending' where status is null;
update public.events set published=false where published is null;
update public.ideas set status='pending' where status is null;
update public.ideas set published=false where published is null;
update public.noticeboard set status='pending' where status is null;
update public.noticeboard set published=false where published is null;

-- RLS
alter table public.news enable row level security;
alter table public.events enable row level security;
alter table public.ideas enable row level security;
alter table public.noticeboard enable row level security;

-- Recreate workflow policies
drop policy if exists "public approved news" on public.news;
create policy "public approved news" on public.news for select using (status='approved' and published=true);
drop policy if exists "public news submissions" on public.news;
create policy "public news submissions" on public.news for insert to anon, authenticated with check (status='pending' and published=false);
drop policy if exists "admin manage news" on public.news;
create policy "admin manage news" on public.news for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public approved events" on public.events;
create policy "public approved events" on public.events for select using (status='approved' and published=true);
drop policy if exists "public event submissions" on public.events;
create policy "public event submissions" on public.events for insert to anon, authenticated with check (status='pending' and published=false);
drop policy if exists "admin manage events" on public.events;
create policy "admin manage events" on public.events for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public approved ideas" on public.ideas;
create policy "public approved ideas" on public.ideas for select using (status='approved' and published=true);
drop policy if exists "public idea submissions" on public.ideas;
create policy "public idea submissions" on public.ideas for insert to anon, authenticated with check (status='pending' and published=false);
drop policy if exists "admin manage ideas" on public.ideas;
create policy "admin manage ideas" on public.ideas for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public approved noticeboard" on public.noticeboard;
create policy "public approved noticeboard" on public.noticeboard for select using (status='approved' and published=true);
drop policy if exists "public noticeboard submissions" on public.noticeboard;
create policy "public noticeboard submissions" on public.noticeboard for insert to anon, authenticated with check (status='pending' and published=false);
drop policy if exists "admin manage noticeboard" on public.noticeboard;
create policy "admin manage noticeboard" on public.noticeboard for all to authenticated using (public.is_admin()) with check (public.is_admin());

create index if not exists news_status_published_idx on public.news(status,published,created_at desc);
create index if not exists events_status_published_idx on public.events(status,published,event_date);
create index if not exists ideas_status_published_idx on public.ideas(status,published,created_at desc);
create index if not exists noticeboard_status_published_idx on public.noticeboard(status,published,notice_date desc,created_at desc);

select 'PHASE 4 FINAL SQL SUCCESS' as result;

-- ===== PERSONALITY APPROVAL FIX =====
drop function if exists public.approve_personality_submission(uuid);
drop function if exists public.approve_personality_submission(bigint);
create or replace function public.approve_personality_submission(submission_id bigint)
returns void language plpgsql security definer set search_path=public as $$
declare s public.personality_submissions%rowtype;
begin
  if not public.is_admin() then raise exception 'Not authorized'; end if;
  select * into s from public.personality_submissions where id=submission_id and status='pending' for update;
  if not found then raise exception 'Pending personality submission not found'; end if;
  insert into public.personalities(name,photo_url,relation_to_kurduwadi,field,major_work,reference_url,contact,status,created_at,updated_at)
  values(s.name,s.image_url,s.relation,s.field,s.reason,s.reference_url,s.contact,'approved',coalesce(s.created_at,now()),now());
  update public.personality_submissions set status='approved' where id=submission_id;
end; $$;
revoke all on function public.approve_personality_submission(bigint) from public;
grant execute on function public.approve_personality_submission(bigint) to authenticated;
alter table public.personalities enable row level security;
drop policy if exists personalities_public_approved on public.personalities;
create policy personalities_public_approved on public.personalities for select using (status='approved');
create index if not exists personalities_status_created_idx on public.personalities(status,created_at desc);
