-- KURDUWADI CITY PORTAL - SUPABASE DATABASE
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  education text,
  job text,
  city text not null,
  state text default 'Maharashtra',
  country text default 'India',
  blood_group text,
  skills text,
  phone text,
  is_public boolean default false,
  blood_public boolean default false,
  status text default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz default now()
);

create table if not exists public.admin_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin',
  created_at timestamptz default now()
);

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  category text default 'शहर',
  image_url text,
  author_name text,
  author_phone text,
  source_url text,
  published boolean default false,
  status text default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_date date,
  event_time text,
  location text,
  description text not null,
  organizer text,
  contact text,
  image_url text,
  published boolean default false,
  status text default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text,
  image_url text not null,
  published boolean default true,
  created_at timestamptz default now()
);

-- Safe admin check. Add only trusted auth.users IDs to admin_profiles.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (select 1 from public.admin_profiles where id = auth.uid() and role = 'admin');
$$;

alter table public.profiles enable row level security;
alter table public.admin_profiles enable row level security;
alter table public.news enable row level security;
alter table public.events enable row level security;
alter table public.gallery enable row level security;

-- PROFILES
 drop policy if exists "public approved profiles" on public.profiles;
create policy "public approved profiles" on public.profiles for select using (status='approved' and is_public=true);
drop policy if exists "public profile submissions" on public.profiles;
create policy "public profile submissions" on public.profiles for insert to anon, authenticated with check (status='pending');
drop policy if exists "admin manage profiles" on public.profiles;
create policy "admin manage profiles" on public.profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- NEWS: visitors can submit, but only approved+published news is public.
drop policy if exists "public approved news" on public.news;
create policy "public approved news" on public.news for select using (status='approved' and published=true);
drop policy if exists "public news submissions" on public.news;
create policy "public news submissions" on public.news for insert to anon, authenticated with check (status='pending' and published=false);
drop policy if exists "admin manage news" on public.news;
create policy "admin manage news" on public.news for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- EVENTS
drop policy if exists "public approved events" on public.events;
create policy "public approved events" on public.events for select using (status='approved' and published=true);
drop policy if exists "public event submissions" on public.events;
create policy "public event submissions" on public.events for insert to anon, authenticated with check (status='pending' and published=false);
drop policy if exists "admin manage events" on public.events;
create policy "admin manage events" on public.events for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- GALLERY
drop policy if exists "public gallery" on public.gallery;
create policy "public gallery" on public.gallery for select using (published=true);
drop policy if exists "admin manage gallery" on public.gallery;
create policy "admin manage gallery" on public.gallery for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- COMMUNITY IDEAS
create table if not exists public.ideas (
  id bigint generated by default as identity primary key,
  name text,
  area text,
  title text not null,
  description text not null,
  contact text,
  image_url text,
  status text default 'pending' check (status in ('pending','approved','rejected')),
  published boolean default false,
  created_at timestamptz default now()
);

alter table public.ideas enable row level security;
drop policy if exists "public approved ideas" on public.ideas;
create policy "public approved ideas" on public.ideas for select using (status='approved' and published=true);
drop policy if exists "public idea submissions" on public.ideas;
create policy "public idea submissions" on public.ideas for insert to anon, authenticated with check (status='pending' and published=false);
drop policy if exists "admin manage ideas" on public.ideas;
create policy "admin manage ideas" on public.ideas for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- IMAGE STORAGE/CDN: Supabase Storage serves files through its CDN.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('community-images','community-images',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=true, file_size_limit=5242880, allowed_mime_types=array['image/jpeg','image/png','image/webp'];

drop policy if exists "public read community images" on storage.objects;
create policy "public read community images" on storage.objects for select using (bucket_id='community-images');
drop policy if exists "anon upload community images" on storage.objects;
create policy "anon upload community images" on storage.objects for insert to anon, authenticated with check (bucket_id='community-images');
drop policy if exists "admin delete community images" on storage.objects;
create policy "admin delete community images" on storage.objects for delete to authenticated using (bucket_id='community-images' and public.is_admin());

create index if not exists profiles_city_idx on public.profiles(city);
create index if not exists profiles_status_public_idx on public.profiles(status,is_public);
create index if not exists news_status_published_idx on public.news(status,published,created_at desc);
create index if not exists events_status_published_idx on public.events(status,published,event_date);
